name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to be released'
        default: '0.0.1'
        required: true
        type: string

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        if: env.RELEASE_NAME == 'aarch64-unknown-linux-gnu'
        id: release
        uses: softprops/action-gh-release@v2
        env:
          RELEASE_NAME: v${{ inputs.version }}
        with:
          token: ${{ secrets.PAT }}
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}

  build-release:
    name: build-release
    # needs: ['create-release']
    runs-on: ${{ matrix.os }}
    env:
      TARGET_DIR: ./target
      APP_NAME: gid
      RELEASE_NAME: v${{ inputs.version }}
    strategy:
      matrix:
        build:
          - linux_x86_x64
          - linux_aarch64
          - macos
        include:
        - build: linux_x86_x64
          os: ubuntu-latest
          rust: stable
          target: x86_64-unknown-linux-gnu
          cross: true
          linker: ""

        - build: linux_aarch64
          os: ubuntu-latest
          rust: stable
          target: aarch64-unknown-linux-gnu
          cross: true
          linker: gcc-aarch64-linux-gnu

        - build: macos
          os: macos-latest
          rust: stable
          target: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install aarch64-unknown-linux-gnu deps
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install Linker
        if: matrix.cross
        run: |
          sudo apt update
          sudo apt install ${{ matrix.linker }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} --target-dir ${{ env.TARGET_DIR }}
      
      - name: Strip binary (Linux x86_x64 and MacOS)
        if: matrix.target == 'x86_64-unknown-linux-gnu' || matrix.target == 'aarch64-apple-darwin'
        run: strip "target/${{ matrix.target }}/release/${{ env.APP_NAME }}"

      - name: Strip binary (Linux aarch64)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: aarch64-linux-gnu-strip "target/${{ matrix.target }}/release/${{ env.APP_NAME }}"

      - name: Build archive
        shell: bash
        run: |
          staging="${{ env.APP_NAME }}-${{ env.RELEASE_NAME }}-${{ matrix.target }}"
          mkdir "$staging"
          cp {README.md,LICENSE} "$staging/"

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "target/${{ matrix.target }}/release/${{ env.APP_NAME }}.exe" "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp "target/${{ matrix.target }}/release/${{ env.APP_NAME }}" "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Upload release archive
        if: env.RELEASE_NAME == 'aarch64-unknown-linux-gnu'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ${{ env.ASSET }}
          repo-token: ${{ secrets.PAT }}
          release-tag: ${{ env.RELEASE_NAME }}
